-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 15:22:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursos` (
  `Banco de dados` VARCHAR(100) NOT NULL,
  `Frontend` VARCHAR(100) NULL,
  `Backend` VARCHAR(100) NULL,
  `Turmas_Turma front` VARCHAR(100) NOT NULL,
  `Turmas_Turmas Banco de dados` VARCHAR(100) NOT NULL,
  `Turmas_Turma back` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Turmas_Turma front`, `Turmas_Turmas Banco de dados`, `Turmas_Turma back`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turmas` (
  `Turma front` VARCHAR(100) NOT NULL,
  `Turmas Banco de dados` VARCHAR(100) NOT NULL,
  `Turma back` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Turma front`, `Turmas Banco de dados`, `Turma back`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alunos` (
  `Nome` VARCHAR(100) NOT NULL,
  `Sobrenomes` VARCHAR(100) NOT NULL,
  `Dados alunos_Endereco` VARCHAR(100) NOT NULL,
  `Dados alunos_Numero` INT(100) NOT NULL,
  `Dados alunos_Endereco1` VARCHAR(100) NOT NULL,
  `Dados alunos_Numero1` INT(100) NOT NULL,
  PRIMARY KEY (`Nome`, `Sobrenomes`, `Dados alunos_Endereco`, `Dados alunos_Numero`, `Dados alunos_Endereco1`, `Dados alunos_Numero1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turmas_has_Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turmas_has_Turmas` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alunos_has_Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alunos_has_Turmas` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turmas_has_Turmas1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turmas_has_Turmas1` (
  `Turmas_Turma front` VARCHAR(100) NOT NULL,
  `Turmas_Turmas Banco de dados` VARCHAR(100) NOT NULL,
  `Turmas_Turma back` VARCHAR(100) NOT NULL,
  `Turmas_Turma front1` VARCHAR(100) NOT NULL,
  `Turmas_Turmas Banco de dados1` VARCHAR(100) NOT NULL,
  `Turmas_Turma back1` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Turmas_Turma front`, `Turmas_Turmas Banco de dados`, `Turmas_Turma back`, `Turmas_Turma front1`, `Turmas_Turmas Banco de dados1`, `Turmas_Turma back1`),
  INDEX `fk_Turmas_has_Turmas1_Turmas1_idx` (`Turmas_Turma front1` ASC, `Turmas_Turmas Banco de dados1` ASC, `Turmas_Turma back1` ASC) VISIBLE,
  INDEX `fk_Turmas_has_Turmas1_Turmas_idx` (`Turmas_Turma front` ASC, `Turmas_Turmas Banco de dados` ASC, `Turmas_Turma back` ASC) VISIBLE,
  CONSTRAINT `fk_Turmas_has_Turmas1_Turmas`
    FOREIGN KEY (`Turmas_Turma front` , `Turmas_Turmas Banco de dados` , `Turmas_Turma back`)
    REFERENCES `mydb`.`Turmas` (`Turma front` , `Turmas Banco de dados` , `Turma back`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turmas_has_Turmas1_Turmas1`
    FOREIGN KEY (`Turmas_Turma front1` , `Turmas_Turmas Banco de dados1` , `Turmas_Turma back1`)
    REFERENCES `mydb`.`Turmas` (`Turma front` , `Turmas Banco de dados` , `Turma back`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turmas_has_Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turmas_has_Alunos` (
  `Turmas_Turma front` VARCHAR(100) NOT NULL,
  `Turmas_Turmas Banco de dados` VARCHAR(100) NOT NULL,
  `Turmas_Turma back` VARCHAR(100) NOT NULL,
  `Alunos_Nome` VARCHAR(100) NOT NULL,
  `Alunos_Sobrenomes` VARCHAR(100) NOT NULL,
  `Alunos_Dados alunos_Endereco` VARCHAR(100) NOT NULL,
  `Alunos_Dados alunos_Numero` INT(100) NOT NULL,
  PRIMARY KEY (`Turmas_Turma front`, `Turmas_Turmas Banco de dados`, `Turmas_Turma back`, `Alunos_Nome`, `Alunos_Sobrenomes`, `Alunos_Dados alunos_Endereco`, `Alunos_Dados alunos_Numero`),
  INDEX `fk_Turmas_has_Alunos_Alunos1_idx` (`Alunos_Nome` ASC, `Alunos_Sobrenomes` ASC, `Alunos_Dados alunos_Endereco` ASC, `Alunos_Dados alunos_Numero` ASC) VISIBLE,
  INDEX `fk_Turmas_has_Alunos_Turmas1_idx` (`Turmas_Turma front` ASC, `Turmas_Turmas Banco de dados` ASC, `Turmas_Turma back` ASC) VISIBLE,
  CONSTRAINT `fk_Turmas_has_Alunos_Turmas1`
    FOREIGN KEY (`Turmas_Turma front` , `Turmas_Turmas Banco de dados` , `Turmas_Turma back`)
    REFERENCES `mydb`.`Turmas` (`Turma front` , `Turmas Banco de dados` , `Turma back`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turmas_has_Alunos_Alunos1`
    FOREIGN KEY (`Alunos_Nome` , `Alunos_Sobrenomes` , `Alunos_Dados alunos_Endereco` , `Alunos_Dados alunos_Numero`)
    REFERENCES `mydb`.`Alunos` (`Nome` , `Sobrenomes` , `Dados alunos_Endereco` , `Dados alunos_Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos_has_Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursos_has_Turmas` (
  `Cursos_Turmas_Turma front` VARCHAR(100) NOT NULL,
  `Cursos_Turmas_Turmas Banco de dados` VARCHAR(100) NOT NULL,
  `Cursos_Turmas_Turma back` VARCHAR(100) NOT NULL,
  `Turmas_Turma front` VARCHAR(100) NOT NULL,
  `Turmas_Turmas Banco de dados` VARCHAR(100) NOT NULL,
  `Turmas_Turma back` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Cursos_Turmas_Turma front`, `Cursos_Turmas_Turmas Banco de dados`, `Cursos_Turmas_Turma back`, `Turmas_Turma front`, `Turmas_Turmas Banco de dados`, `Turmas_Turma back`),
  INDEX `fk_Cursos_has_Turmas_Turmas1_idx` (`Turmas_Turma front` ASC, `Turmas_Turmas Banco de dados` ASC, `Turmas_Turma back` ASC) VISIBLE,
  INDEX `fk_Cursos_has_Turmas_Cursos1_idx` (`Cursos_Turmas_Turma front` ASC, `Cursos_Turmas_Turmas Banco de dados` ASC, `Cursos_Turmas_Turma back` ASC) VISIBLE,
  CONSTRAINT `fk_Cursos_has_Turmas_Cursos1`
    FOREIGN KEY (`Cursos_Turmas_Turma front` , `Cursos_Turmas_Turmas Banco de dados` , `Cursos_Turmas_Turma back`)
    REFERENCES `mydb`.`Cursos` (`Turmas_Turma front` , `Turmas_Turmas Banco de dados` , `Turmas_Turma back`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Turmas_Turmas1`
    FOREIGN KEY (`Turmas_Turma front` , `Turmas_Turmas Banco de dados` , `Turmas_Turma back`)
    REFERENCES `mydb`.`Turmas` (`Turma front` , `Turmas Banco de dados` , `Turma back`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alunos_has_Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alunos_has_Cursos` (
  `Alunos_Nome` VARCHAR(100) NOT NULL,
  `Alunos_Sobrenomes` VARCHAR(100) NOT NULL,
  `Alunos_Dados alunos_Endereco` VARCHAR(100) NOT NULL,
  `Alunos_Dados alunos_Numero` INT(100) NOT NULL,
  `Alunos_Dados alunos_Endereco1` VARCHAR(100) NOT NULL,
  `Alunos_Dados alunos_Numero1` INT(100) NOT NULL,
  `Cursos_Turmas_Turma front` VARCHAR(100) NOT NULL,
  `Cursos_Turmas_Turmas Banco de dados` VARCHAR(100) NOT NULL,
  `Cursos_Turmas_Turma back` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Alunos_Nome`, `Alunos_Sobrenomes`, `Alunos_Dados alunos_Endereco`, `Alunos_Dados alunos_Numero`, `Alunos_Dados alunos_Endereco1`, `Alunos_Dados alunos_Numero1`, `Cursos_Turmas_Turma front`, `Cursos_Turmas_Turmas Banco de dados`, `Cursos_Turmas_Turma back`),
  INDEX `fk_Alunos_has_Cursos_Cursos1_idx` (`Cursos_Turmas_Turma front` ASC, `Cursos_Turmas_Turmas Banco de dados` ASC, `Cursos_Turmas_Turma back` ASC) VISIBLE,
  INDEX `fk_Alunos_has_Cursos_Alunos1_idx` (`Alunos_Nome` ASC, `Alunos_Sobrenomes` ASC, `Alunos_Dados alunos_Endereco` ASC, `Alunos_Dados alunos_Numero` ASC, `Alunos_Dados alunos_Endereco1` ASC, `Alunos_Dados alunos_Numero1` ASC) VISIBLE,
  CONSTRAINT `fk_Alunos_has_Cursos_Alunos1`
    FOREIGN KEY (`Alunos_Nome` , `Alunos_Sobrenomes` , `Alunos_Dados alunos_Endereco` , `Alunos_Dados alunos_Numero` , `Alunos_Dados alunos_Endereco1` , `Alunos_Dados alunos_Numero1`)
    REFERENCES `mydb`.`Alunos` (`Nome` , `Sobrenomes` , `Dados alunos_Endereco` , `Dados alunos_Numero` , `Dados alunos_Endereco1` , `Dados alunos_Numero1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alunos_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_Turmas_Turma front` , `Cursos_Turmas_Turmas Banco de dados` , `Cursos_Turmas_Turma back`)
    REFERENCES `mydb`.`Cursos` (`Turmas_Turma front` , `Turmas_Turmas Banco de dados` , `Turmas_Turma back`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
